### ISSUE TITLE
Textfehler

### ISSUE THREAD

**Issue by gitlyap** [TUD-RST/MSRM#2]
Hi,
in der PDF fehlt auf Seite 13 ein "wird": "Im Hauptteil des Skripts WIRD ...".

Viele Gruesse

PS: Vielen Dank fuer das Repo. Es ist sehr hilfreich zum verstehen des Buchs. Waere schoen, wenn du die (Kurz-)Beschreibung des Repos noch anpassen koenntest (MSRM war nicht so hilfreich ;-)), damit ersichtlich wird, dass das zu dem Buch gehoert.

**Comment by cknoll** [comment]
Vielen Dank für den Hinweis. Korrigiere ich nächste Woche.

**Comment by cknoll** [comment]
Erledigt.
